"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 5.x.

For more information on this file, see
https://docs.djangoproject.com/en/5.x/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.x/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.x/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'dev-secret-key-not-for-production-use-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = 'DEVELOPMENT' in os.environ

ALLOWED_HOSTS = [
    '.orderimo.com',
    '.herokuapp.com',
    '.gitpod.io',
    'localhost',
    '127.0.0.1',
    '192.168.0.59',
    '0.0.0.0',
    'testserver',
]


# Live Site Link
# Site Identity
SITE_NAME = "Orderimo"
SITE_DOMAIN = "orderimo.com"
STORENAME = "Orderimo"

if 'DEVELOPMENT' in os.environ:
    LIVE_LINK = 'http://127.0.0.1:8023/'
else:
    LIVE_LINK = 'https://orderimo.com/'


# Application definition
INSTALLED_APPS = [
    # custom admin
    'jazzmin',
    # django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'analytics',
    'analytics',
    # allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # custom
    'home',
    'products',
    'bag',
    'wishlist',
    'checkout',
    'tracking',
    'profiles',
    'about',
    'blog',
    'avatar',
    'accounts',
    'stores',
    'notifications',
    'invoices',
    'coupons',
    'newsletter',
    'subscriptions',
    # other
    'crispy_forms',
    'crispy_bootstrap5',
    'storages',
    'ckeditor',  # for editing text input
    'rest_framework',
    'django_ratelimit',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'checkout.middleware.AbandonedCartMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'templates', 'allauth'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # required by allauth
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'ecommerce.store_context.store_context',
                'ecommerce.admin_context.admin_store_stats',
                # 'ecommerce.context_processors.currency_context',  # Not implemented yet
                'bag.contexts.bag_contents',  # required for shopping bag
                'wishlist.context_processors.wishlist_context',
                # 'comparison.context_processors.compare_context',
            ],
            'builtins': [
                'crispy_forms.templatetags.crispy_forms_tags',
                'crispy_forms.templatetags.crispy_forms_field',
            ]
        },
    },
]

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds (Django 5 default)

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

ACCOUNT_LOGIN_METHODS = {'email', 'username'}
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_SIGNUP_FIELDS = ['email*', 'email2*', 'username*', 'password1*', 'password2*']
ACCOUNT_USERNAME_MIN_LENGTH = 4
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
# Login rate limiting (allauth 65.x)
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/10m',
}

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.x/ref/settings/#databases

if 'DATABASE_URL' in os.environ:
    DATABASES = {
        'default': dj_database_url.parse(os.environ.get('DATABASE_URL'))
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.x/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.x/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.x/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.x/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cache — use LocMemCache for dev; silence django_ratelimit E003 (requires Redis)
# which is a pre-existing project config issue, not a Phase 7/9 implementation error
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'orderimo-dev-cache',
    }
}
SILENCED_SYSTEM_CHECKS = ['django_ratelimit.E003']

# AWS Settings
if 'USE_AWS' in os.environ:
    # Cache control
    AWS_S3_OBJECT_PARAMETERS = {
        'Expires': 'Thu, 31 Dec 2099 20:00:00 GMT',
        'CacheControl': 'max-age=94608000',
    }

    # Bucket Config
    AWS_STORAGE_BUCKET_NAME = 'kc-ecommerce'
    AWS_S3_REGION_NAME = 'eu-north-1'
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'

    # Static and media files
    STATICFILES_STORAGE = 'custom_storages.StaticStorage'
    STATICFILES_LOCATION = 'static'
    DEFAULT_FILE_STORAGE = 'custom_storages.MediaStorage'
    MEDIAFILES_LOCATION = 'media'

    # Override static and media URLs in production
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{STATICFILES_LOCATION}/'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{MEDIAFILES_LOCATION}/'
else:
    # Local development: use WhiteNoise for compressed static files
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Stripe & Delivery
FREE_DELIVERY_THRESHOLD = 80
STANDARD_DELIVERY_PERCENTAGE = 20
STRIPE_CURRENCY = 'eur'
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY', '')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WH_SECRET = os.getenv('STRIPE_WH_SECRET', '')

# Multi-Currency Settings (EUR base, USD/GBP via Frankfurter API)
CURRENCIES = ['EUR', 'USD', 'GBP']
DEFAULT_CURRENCY = 'EUR'
CURRENCY_RATES = {}  # cache populated at runtime by currency.py

# CoinGate API key for XMR payments
COINGATE_API_KEY = os.getenv('COINGATE_API_KEY', '')

# =============================================================================
# Mailchimp Newsletter Settings
# =============================================================================
# Get these from your Mailchimp account dashboard
# API Key: Account -> Extras -> API Keys
# Server prefix: found at the end of your API key after the dash (e.g. "us6")
# List IDs: Audience -> Settings -> Audience name and defaults
MAILCHIMP_API_KEY = os.environ.get('MAILCHIMP_API_KEY', '')
MAILCHIMP_SERVER = os.environ.get('MAILCHIMP_SERVER', 'us1')  # e.g. 'us1', 'us6', 'us20'

# Map each store slug to its Mailchimp Audience List ID
MAILCHIMP_LIST_IDS = {
    'orderimo': os.environ.get('MAILCHIMP_LIST_ID_ORDERIMO', ''),
    'petshop-ie': os.environ.get('MAILCHIMP_LIST_ID_PETSHOP', ''),
    'digitalhub': os.environ.get('MAILCHIMP_LIST_ID_DIGITAL', ''),
}

if 'DEVELOPMENT' in os.environ:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'hello@orderimo.com'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_USE_TLS = True
    EMAIL_PORT = 587
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASS')
    DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_HOST_USER') or 'hello@orderimo.com'


# Site Logo
SITE_LOGO = 'favicon/android-chrome-192x192.png'

# Tracking
TRACKING_BASE_URL = os.environ.get('TRACKING_BASE_URL', 'https://orderimo.com')


# =============================================================================
# SECURITY HARDENING (Phase 8)
# =============================================================================

# Clickjacking protection
X_FRAME_OPTIONS = 'DENY'

# XSS protection (legacy but still useful)
SECURE_BROWSER_XSS_FILTER = True

# Content type sniffing protection
SECURE_CONTENT_TYPE_NOSNIFF = True
X_CONTENT_TYPE_OPTIONS = 'nosniff'

# Session security
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# CSRF security
CSRF_COOKIE_HTTPONLY = True

# Account security (allauth) - rate limits set via ACCOUNT_RATE_LIMITS above

# =============================================================================
# PRODUCTION-ONLY SECURITY SETTINGS
# These only apply when DEBUG=False (i.e. in production)
# =============================================================================
if not DEBUG and not os.environ.get('TESTING'):
    # Force HTTPS
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year

    # Secure cookies (only sent over HTTPS)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Wagtail Admin customization
WAGTAILADMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "Orderimo Admin",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "Orderimo",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "Orderimo",

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": SITE_LOGO,

    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": SITE_LOGO,

    # Logo to use for login form in dark themes (defaults to login_logo)
    "login_logo_dark": SITE_LOGO,

    # Custom user avatar function to display their Punk
    "user_avatar": SITE_LOGO,

    # Welcome text on the login screen
    "welcome_sign": "Welcome to the Orderimo Admin Portal",

    # Copyright on the footer
    "copyright": "Orderimo Ltd 2026",

    # List of model admins to search from the search bar, search bar omitted if excluded
    # If you want to use a single search field you dont need to use a list, you can use a simple string
    "search_model": ["auth.User", "blog.blogpage", "about.aboutpage"],

    # Form Template Type
    "changeform_format": "collapsible",

    # Top Menu:

    # Links to put along the top menu
    "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},

        # external url that opens in a new window (Permissions can be added)
        {"name": "Site Link", "url": LIVE_LINK, "new_window": True},

        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app": "products"},

        # model admin to link to (Permissions checked against model)
        {"model": "avatar.avatar"},
    ],

    # User Menu:

    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        {"name": "Site Link", "url": LIVE_LINK, "new_window": True},
        {"model": "products.product"},
        {"model": "products.category"},
        {"model": "auth.user"},
        {"model": "avatar.avatar"},
        {"model": "blog.blogpage"},
        {"model": "about.aboutpage"},
        {"name": "Developer", "url": "https://github.com/Ada-555/Orderimo", "new_window": True},
    ],
}
