# Generated by Django 5.2 on 2026-03-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
