# Generated by Django 5.2.11 on 2026-03-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='store',
            field=models.CharField(blank=True, default='orderimo', max_length=50),
        ),
    ]
