# Generated by Django 5.2.11 on 2026-03-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_add_status_and_estimated_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, help_text='Shipping carrier name (e.g. An Post, DPD)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Carrier tracking number', max_length=100, null=True),
        ),
    ]
