# Generated by Django 5.2.11 on 2026-03-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_add_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='crypto_address',
            field=models.CharField(blank=True, help_text='Destination crypto wallet address', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='crypto_amount',
            field=models.DecimalField(blank=True, decimal_places=12, help_text='Crypto amount sent (for XMR via CoinGate)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='crypto_txid',
            field=models.CharField(blank=True, help_text='Cryptocurrency transaction ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('stripe_crypto', 'Stripe Crypto (BTC/USDC)'), ('coingate_xmr', 'CoinGate (XMR)')], default='card', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.CharField(choices=[('orderimo', 'Orderimo'), ('petshop-ie', 'PetShop Ireland'), ('digitalhub', 'DigitalHub')], default='orderimo', max_length=20),
        ),
    ]
