# Generated by Django 5.2.11 on 2026-03-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_add_store_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_codes',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list of applied coupon codes', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total discount from applied coupons', max_digits=10),
        ),
    ]
