# Generated by Django 5.2.11 on 2026-03-29 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_coupon_codes_order_coupon_discount'),
        ('profiles', '0003_remove_userprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbandonedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Django session key for anonymous carts', max_length=40, null=True)),
                ('email', models.EmailField(help_text='Email address to send the reminder to', max_length=254)),
                ('store', models.CharField(choices=[('orderimo', 'Orderimo'), ('petshop-ie', 'PetShop Ireland'), ('digitalhub', 'DigitalHub')], default='orderimo', max_length=20)),
                ('bag_snapshot', models.TextField(default='{}')),
                ('bag_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_converted', models.BooleanField(default=False)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_coupon_code', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abandoned_carts', to='profiles.userprofile')),
            ],
            options={
                'verbose_name': 'Abandoned Cart',
                'verbose_name_plural': 'Abandoned Carts',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['email', 'store', 'is_converted'], name='checkout_ab_email_e0f21e_idx'), models.Index(fields=['last_activity'], name='checkout_ab_last_ac_61c133_idx')],
            },
        ),
    ]
