# Generated by Django 5.2.11 on 2026-03-29 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_product_is_subscription_product_stripe_price_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(choices=[('orderimo', 'Orderimo'), ('petshop-ie', 'PetShop Ireland'), ('digitalhub', 'DigitalHub')], default='orderimo', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkout_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bag',
                'verbose_name_plural': 'Bags',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BagItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('size', models.CharField(blank=True, help_text='Size code if product has sizes (e.g., S, M, L, XL)', max_length=2, null=True)),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bag.bag')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Bag Item',
                'verbose_name_plural': 'Bag Items',
            },
        ),
    ]
