# Generated by Django 5.2 on 2026-03-29 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('theme', models.CharField(choices=[('cyan', 'Cyan/Neon (Orderimo)'), ('green', 'Green/Earthy (PetShop Ireland)'), ('purple', 'Purple/Modern (DigitalHub)')], default='cyan', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('footer_text', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_config', to='sites.site')),
            ],
        ),
    ]
