# Generated by Django 5.2 on 2026-03-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='download_file',
            field=models.FileField(blank=True, null=True, upload_to='downloads/'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_digital',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='low_stock_threshold',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='views_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
