# Generated by Django 5.2.11 on 2026-03-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='stock_qty_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='featured_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='category_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='rating_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='variant_sku_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.CharField(blank=True, default='orderimo', help_text='Store slug this product belongs to: orderimo, petshop-ie, digitalhub', max_length=50),
        ),
    ]
