# Generated by Django 5.2.11 on 2026-03-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_subscription',
            field=models.BooleanField(default=False, help_text='Enable this product as a recurring subscription'),
        ),
        migrations.AddField(
            model_name='product',
            name='stripe_price_id',
            field=models.CharField(blank=True, default='', help_text='Stripe Price ID for subscription billing', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='subscription_interval',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='', help_text='Billing interval for subscription', max_length=20),
        ),
    ]
